SAMPLE_FEEDBACK = [
    "This talks about what workers can do but makes no mention of the ventilation. This completely misses the point of the question",
    "the answer made no mention about workplace ventilation",
    "The question is asking about workplace ventilation but the answer is all about N95 masks. This is not relevant making it a bad answer",
    "the answer is off topic and does not answer the question",
    "This does a good job answering the question without getting too detailed. I feel like there could be a little more information but it does answer what's being asked",
    "the answer was on point and answered the question well",
    "Discusses potential travel restrictions for international travelers, though without specific information for any country.",
    "This broadly answers the question that will be differences to international travel but does not give specifics on what will change when departing.",
    "Has advice that's relevant if the destination of your international travel is the US.",
    "This answers what will happen when arriving at a destination but not when departing.",
    "Directly answers the question by explaining additional exit screening may be necessary.",
    "The question was answered with specific examples.",
    "The answer gives strong suggestions as to what should be on the top of the priority list to successfully develop and execute a plan to protect from the Covid virus.",
    "This is a much more detailed and specific list of things that you can do for your emergency plan in your house. This seems to be exactly what the question was looking for.",
    "The answer gives a few suggestions but it is very brief and should be better detailed or explained further.",
    "This answer is talking about emergency plans for mass gatherings but I think the question mostly wanted to know about general family emergency plans",
    "Seems like an answer that is light on information but it does address what's being asked. Provides a link to local health departments to help with putting an emergency plan in place which is helpful",
    "The answer gives guidance on how to go about creating steps for a plan that suits your needs. It is not specific to the point that it lists items, but it does tell you what to make sure to include so you can come up with a plan to suit your families needs.",
    "It answers the question as far as saying that the risk is increase for traveling to visit family, or for certain conditions when going camping, but doesn't really say if it is OK to do so.",
    "The question posed 2 distinct scenarios and this answer specifically answers both of them making it an excellent response",
    "The answer does not address camping at all. It does recommend not visiting older family members.",
    "This is ok because it mentions what type of people you should distance yourself from but makes no mention of camping",
    "The question addresses traveling to visit family, but doesn't say anything about camping specifically.",
    "This only talks about general travel but doesn't mention meeting with other people (family) or camping like the question asked",
    "Gives guidance on how law enforcement should interact with live individuals infected with COVD-19. Doesn't mention death inquiries at all.",
    "This answer is excellent because it refers to law enforcement explicitly, and provides a lot of detailed information as to how law enforcement can stay safe while working during the pandemic.",
    "Doesn't mention death inquiries, instead giving generic advice about when law enforcement personnel should self-isolate.",
    "This answer is bad because it does not answer the question, even though it does refer to law enforcement workers. The answer does not provide information as to how law enforcement can stay safe while working with bodies.",
    "Has clear and detailed information about handling dead bodies contaminated with COVID-19.",
    "This answer is excellent because it provides detailed information as to how law enforcement workers can stay safe from COVID while working with dead bodies, which answers the question entirely.",
    "Fully answers question with relevant information and provides links for further reading.",
    "This is a detailed list of when it is safe for someone who has had the disease, but hasn't been tested to see if they no longer have it.",
    "Only part of the question is answered. Answer should also have information regarding testing.",
    "This has a detailed list of recommendations for how to know if it's safe for you to go outside and when to stay in if you haven't yet been tested for COVID-19.",
    "Question is regarding covid testing and isolation/social distancing guidelines; answer is irrelevant to this and explains cleaning/disinfecting your home.",
    "This is about how to clean your home, not how to know if it's safe to go outside.",
    "The answer is about HIV.  The question given was not about HIV.",
    "This answer is irrelevant to the question. This answer provides information about Covid-19 and people with HIV and the question is asking about the increased risk of Covid-19 infection on people with hepatocellular carcinoma.",
    "This answers the question directly by providing known information on patients with hepatocellular carcinoma and the risk of getting infected by Covid-19.",
    "This gives a decent amount of information and it specifically mentions the condition.  I think it's a good answer.",
    "The disease that is asked about is not the one that is mentioned in the passage.  I'm not sure it would help someone that is querying the information shown.",
    "This information does not answer the question. The question is asking about the risk of Covid-19 on people with hepatocellular carcinoma, however, the answer provides information on elevated ALT and AST in patients with Covid-19 and the recommendation to test them for hepatitis A, hepatitis B and hepatitis C virus infection.",
    "The answer contain steps to be taken in the event of COVID-19 spread.",
    "This answer provides detailed, specific information for what community-based organizations can do in the event of minimal or moderate spread of COVID-19 in the community and thus directly answers the question.",
    "The answer talks about what to do when there's a substantial spread of COVID-19 in the community, even though the question asked for what to do in the event of minimal or moderate spread. It's not the right answer for what's being asked.",
    "The response is perfect because the response highlighted steps to be taken and the appropriate organizations to contact.",
    "The answer is a referral to an official website.",
    "This doesn't directly answer the question at all and instead just provides an external link. While that could be helpful in general, it doesn't specifically address what was being asked.",
    "Specific to the question and thorough explanations are given but is limited in the range of employee positions covered.",
    "This response talks about how customer service reps or gate agents can protect themselves. The question asked about how to stay safe working for an airline. They didn't specify what they do so this answer seems acceptable",
    "This response is geared toward airline catering truck drivers. While the question didn't specify what airline job they were referring to, this one seems extremely specific and maybe too narrow in scope",
    "Thorough explanation but the question is not specific to food handlers/caterers so should include links to other resources.",
    "The question does not state what capacity the worker's job is thus the answer needs links to other position's advices.",
    "This is a good response that talks about how airline passenger service workers can protect themselves. This seems general enough that it would cover the airline workers being asked about",
    "Provides guidance to consumers on getting a test. Doesn't address how healthcare providers can acquire the tests.",
    "Refers to individuals who want to get tested and does not give any guidance that could be helpful to a clinic or individual clinician.",
    "Clear guidance on how clinicians should access tests for COVID-19.",
    "Links are given for clinicians to access the information needed whether it's the Laboratory list or state health departments. There are also recommendations provided for the testing prioritization and specimen collection instructions.",
    "Gives guidance to clinicians to get with their state public health departments as well as a link for more information of lab locations for testing.",
    "Tells clinicians how to access tests and links to points of contact to request kits.",
    "Answer is about isolation rooms for known positive patients. Makes no mention of commercially available virus tests.",
    "The answer does not pertain to respiratory virus panels but towards treatment or examination of already infected patients. The answer addresses what to do once it's too late versus the detection that the query is looking for.",
    "Answer is about disinfection methods, not commercially available virus panels.",
    "The answer refers to disinfecting agents when the query was about respiratory virus panels. Disinfecting agents are not going to help detect the virus or even eliminate it from the air if present.",
    "Clearly answers main question about whether commercially available virus tests can detect coronavirus.",
    'The answer is given directly and straightforwardly immediately and uses the term "respiratory panels" just like in the query so that there is no doubt as to what is being addressed.',
    "It addresses mosquitoes specifically and informs the question asker that they are not the cause of the spread.",
    "The answer states outright that there is no evidence of spread via mosquitoes.",
    "This is more about how the virus originally came from bats and about how coronaviruses in general can be found in other species. It does not address the COVID-19 virus or mosquitoes specifically.",
    "While this discusses animals, transmission and origin of the virus it doesn't specifically answer the question, it never addresses  mosquitos.",
    "It doesn't address mosquitoes at all it speaks only of bats and isn't even general to animals.",
    "The answer is about bats, but does mention that there is no evidence that the virus is present in any wildlife (which would presumably include mosquitoes).",
    "Addresses many aspects of prevention and gives references.",
    "It directly answers the question and gives a link for information on steps to take daily. It also discusses special preventative measure for people with liver disease.",
    "Gives no specifics other than staying at home and references to more information.",
    "While it does mention the topic, it mostly focuses on travel restrictions and meed to include daily living information.",
    "Basic but does address the issues in a broad way.",
    "It answers the question directly. It would be useful to give the specific preventative actions to take, but it does give a link to another page with those.",
    "The question is asking about events.  This answer talks about cleaning, but nothing in specific as pertaining to an event.  The answer is general and not about the question.",
    "This only talks about how to clean a room but this question seems to be more going for contact tracing and what to do in those types of situations so this doesn't match",
    "This does a good job talking specifically about someone getting sick at an event and what to do after that. There are links to additional relevant information which makes it more helpful",
    "This specifically is talking about what to do when a person at an event tests positive.  There is a lot of information provided.",
    "The question is talking about a sick person at an event and this response is for a sick person at your office but the answer still seems to be relevant here. I'd say this is an acceptable answer",
    "This answer doesn't specifically say anything about an event, but the answer has a lot of information that can be used for that question.  I think the information that is provided can help someone who is trying to find out what is to be done when it is found out that a person at an event or any kind of facility tests positive.",
    "This answer does not address if children are capable of transmitting the virus to older members.",
    "This answer is great because it goes into detail about separating children from adults who are at high risk.",
    "This answer does not address specifically if children can spread the disease to older people.",
    "This answer focuses primarily on children rather than children spreading the virus to adults. However there is one sentence that states that children should not be in contact with high risk adults.",
    "This answer does not relate to whether children can spread the disease to others.",
    "This answer says nothing about children spreading the virus to adults.",
    "Provides way too much extraneous information that is irrelevant to the question making the reader search for the answer.",
    "This answer relates to the question and answers it directly.",
    'Not only does this answer the question directly, it is a perfect response and interactive because of the "no." response.',
    "The answer is readily available in the first sentence and the rest is provided as background. It provides a link for more info.",
    "Does not address the question. Provides info about different kinds of masks but nothing about social distancing.",
    "While this relates to face masks and prevention, it does not easily answer the question of whether a face mask can make up for lack of physical distancing.",
    "Specifies that people with asthma are at higher risk for complications from COVID-19 and links to resources for people with asthma.",
    "The answer isn't all about the dangers of having asthma in the pandemic, but it clearly states that having asthma is a risk factor.",
    "Specifically answers the question, saying that people with asthma are at greater risk of severe complications from COVID-19.",
    "The answer is relevant, but it's too short. There's not enough info or evidence.",
]

SAMPLE_QUESTIONS = [
    "Where can I go to get tested for the coronavirus?",
    "What should my facility be testing for?",
    "What should I do if my staff member gets sick at an event we're hosting?",
    "What safety practices shall cruise lines follow in order to ensure that crewmembers safely disembark or transfer to another ship",
    "Why are cloth facemasks recommended instead of medical grade ones?",
    "Can you explain what community mitigation is?",
    "Should my newborn wear a face shield?",
    "Can other medicines be used to cure coronavirus?",
    "What are some factors to think about if there is a group gathering?",
    "Can dogs be brought into the country during COVID 19 outbreak?",
    "How do I best package suspected COVID-19 patient's specimens for shipping?",
    "What is the proper response for a school administrator when a student or staff member it’s confirmed to have COVID-19?",
    "What could I do to protect my employees as a supervisor at a rail transit operation?",
    "What should I do if I think I may have Covid-19?",
    "What should employers of waste collectors do to keep their employees safe?",
    "What kinds of patient gowns should COVID-19 patients wear?",
    "Can I send a COVID-19 test to the CDC for diagnosis?",
    "What information do we know about MIS-C?",
    "Is COVID-19 transmitted through food such as restaurant take out or packaged food?",
    "Am I at risk for COVID-19 if I fly on an airplane?",
    "Are children with underlying health conditions more likely to get sick from coronavirus?",
    "What should I tell my patient if I know they have an underlying issue that puts them at greater risk?",
    "If there is a shortage of respirators, would forceful exhalation during the second stage of labor be considered a priority for a respirator?",
    "What protocols should airline maintenance workers follow to reduce exposure to COVID-19?",
    "Am I at risk for COVID-19 if I fly on an airplane?",
    "What is the definition of clean and disinfecting?",
    "Is it best to clear homeless camps?",
    "How should people that are immuno-compromised protect themselves from COVID?",
    "Which people are at higher risk for severe illness from the COVID-19 virus?",
    "Do I need to adjust the ventilation in my workplace to prevent the spread of COVID-19?",
]
